---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# likelihood.model.series.md

This is an R package for estimating the parameters of a series system model from masked data.
It provides a flexible and intuitive interface for specifying the model and performing maximum
likelihood estimation.

This R package provides a set of functions for
generating MLEs for the lifetime parameters of the components in a series systems and other related characteristics from data that *masks* the component cause of failure, and also the system lifetime.

Masked data comes in a variety of forms:

1. The system lifetime can be masked in three related ways.
   Right censoring occurs when the system under observation
   is only known to have survived for some minimum length of time.
   Left censoring occurs when the system under observation
   is only know to have survived for some maximum length of time.
   Finally, interval censoring occurs when the system under observation
   is only known to have survived between some minimum and maximum
   length of time.

   In the unmasked situation, we know precisely how long the system
   under observation survived.

2. Regardless of how the series system lifetime is masked, the
   lifetime of the components may be masked in any of the ways
   described in item (1). There is, additionally, another kind of
   masking we would like to consider. What if we do not observe
   any of the component lifetimes, and instead are only given
   a (potentially masked) series system lifetime, and a *candidate
   set* of component indexes which plausibly contains the failed
   component index.

   For a series system of $m$ components, the candidate sets are
   subsets of $\{1,\ldots,m\}$.

## Installation

You can install the development version from GitHub with:

```r
# install.packages("devtools")
devtools::install_github("queelius/likelihood.model.series.md")
```

## Usage

This package provides a comprehensive framework for maximum likelihood estimation (MLE) of
series system parameters from masked data.

It is based on a likelihood contribution model, where each kind of masking of component failures
in a series system of some kind and number of components is handled by a set of likelihood
contributions. The likelihood contributions are then combined to form the likelihood model for
the kind of data and series system under consideration.
 
In general, masking models may characaterized by satisfy any (or none) of the following conditions:

Condition 1: The probability that the failed component is in the candidate set is 1.
Condition 2: Given a candidate set of potential causes of failure, when we condition on the
component cause being any one of the components in the candidate set at the given system failure
time, the probability of the candidate set is uniform. 


We provide several kinds of masking models, including:

1. Uninformed candidate sets that satisfy conditions 1, 2, and 3.

2. Candidate sets with relaxed conditions, e.g., informed candidate sets.

Together, these masking models provide a flexible framework for handling a wide variety of
masking situations.

We also provide a method for analyzing the sensitivity of a likelihood model to violations of
the masking assumptions. This is done by providing a set of likelihood models that are
constructed by relaxing the masking assumptions in various ways. The likelihood models are
then compared using the likelihood ratio test.

Other kinds of data and censoring are handled separately by the general likelihood model as
detailed in [likelihood.model](https://github.com/queelius/likelihood.model). This is the general
framework for adding various kinds of contributions to the likelihood model. This package is
focused on providing contributions for masking.

A *general series system* model, and other kinds of series systems, are also handled by external
libraries, such as the [Dynamic Failure Rate](https://github.com/queelius/dfr_dist) library, which
can be used to construct hazard functions for components that may depend on predictors, including time,
any other covariates. 

# Documentation
For more detailed information on how to use this package and what each function does, please refer to the package documentation. The series_system function and its parameters are described in detail there.

# Contributing
Contributions are welcome! Please open an issue or submit a pull request on GitHub if you find any bugs or if you'd like to suggest improvements.

